language: node_js

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#kesäpojat'
        on_success: change
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'
