language: node_js

before_script:
    - npm install -g grunt-cli

after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:

    email: false

    irc:
        channels:
            - 'ircnet.eversible.com#kesapojat-ci'
        on_success: change
        use_notice: true
        skip_join: true
        template:
            - '**'
            - '%{message}'
            - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}'
            - 'Build details : %{build_url}'
            - '**'
